### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by thistehneisen** [OpenByteDev/SourceScraper#3]
```npm i source-scraper

> puppeteer@1.8.0 install /test/node_modules/puppeteer
> node install.js

module.js:549
    throw err;
    ^

Error: Cannot find module '/test/node_modules/puppeteer/install.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm WARN enoent ENOENT: no such file or directory, open '/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.
npm ERR! Linux 4.15.0-30-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "source-scraper"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! puppeteer@1.8.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.8.0 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the puppeteer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs puppeteer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls puppeteer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /test/npm-debug.log```

**Comment by OpenByteDev** [comment]
Could you please provide some more info? With just this I have no idea what could cause this.

**Comment by thistehneisen** [comment]
The npm-debug.log is available through http://lieliskais.es/npm-debug.log

**Comment by ExtinctAmoeba** [comment]
Why this is in **closed** status? Any solution?

**Comment by OpenByteDev** [comment]
This looks more like an issue with puppeteer...
Sorry, I cannot really help you with this.

**Comment by thistehneisen** [comment]
I did manage to install on OS X, so the node_modules were created successfully. Afterwards creating test.js from the example in README.md, as follows:
```
const { scrapers } = require('source-scraper');

(async () => {
    const url = 'https://www.youtube.com/watch?v=SgZ1f4ACZBQ&feature=youtu.be';
    const scraper = scrapers.getFirstApplicable(url);
    const scrap = await scraper.scrap(url);
    if (scrap.success)
        console.log(scrap.data);
})();
```
The output:
```
nils at nilsdigital in ~/C/JavaScript
» node test.js
(node:16410) UnhandledPromiseRejectionWarning: TypeError: scrapers.getFirstApplicable is not a function
    at /Users/nils/Code/JavaScript/test.js:6:30
    at Object.<anonymous> (/Users/nils/Code/JavaScript/test.js:10:3)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:303:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)
(node:16410) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16410) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by OpenByteDev** [comment]
I updated the example:

```js
const { scrapers } = require('source-scraper');

(async () => {
    const url = 'some url';
    const scraper = scrapers.all.getFirstApplicable(url);
    const scrap = await scraper.scrap(url);
    if (scrap.success)
        console.log(scrap.data);
})();
```

**Comment by thistehneisen** [comment]
Creates a new one:
```
nils at nilsdigital in ~/C/JavaScript
» cat test.js
const { scrapers } = require('source-scraper');

(async () => {
    const url = 'https://vidstreaming.io/videos/kaze-ga-tsuyoku-fuiteiru-episode-5';
    const scraper = scrapers.all.getFirstApplicable(url);
    const scrap = await scraper.scrap(url);
    if (scrap.success)
        console.log(scrap.data);
})();
nils at nilsdigital in ~/C/JavaScript
» node test.js
(node:6853) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'scrap' of undefined
    at /Users/nils/Code/JavaScript/test.js:6:33
    at Object.<anonymous> (/Users/nils/Code/JavaScript/test.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:303:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)
(node:6853) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6853) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
